// Generated by scripts/build-vercel-api.mjs. Do not edit by hand.
var __defProp = Object.defineProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// drizzle/schema.ts
var schema_exports = {};
__export(schema_exports, {
  customerHandovers: () => customerHandovers,
  grayCellStatus: () => grayCellStatus,
  individualHandovers: () => individualHandovers,
  misocaStatus: () => misocaStatus,
  storeCheckStates: () => storeCheckStates,
  storesShiftStatus: () => storesShiftStatus,
  taskCategories: () => taskCategories,
  taskDefinitions: () => taskDefinitions,
  taskStates: () => taskStates,
  userRole: () => userRole,
  users: () => users
});
import { bigint, boolean, integer, jsonb, pgEnum, pgTable, serial, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";
var userRole, users, taskStates, storeCheckStates, individualHandovers, customerHandovers, misocaStatus, grayCellStatus, storesShiftStatus, taskCategories, taskDefinitions;
var init_schema = __esm({
  "drizzle/schema.ts"() {
    "use strict";
    userRole = pgEnum("role", ["user", "admin"]);
    users = pgTable("users", {
      /**
       * Surrogate primary key. Auto-incremented numeric value managed by the database.
       * Use this for relations between tables.
       */
      id: serial("id").primaryKey(),
      /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
      openId: varchar("openId", { length: 64 }).notNull().unique(),
      name: text("name"),
      email: varchar("email", { length: 320 }),
      loginMethod: varchar("loginMethod", { length: 64 }),
      role: userRole("role").default("user").notNull(),
      createdAt: timestamp("createdAt").defaultNow().notNull(),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date()),
      lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull()
    });
    taskStates = pgTable("task_states", {
      id: serial("id").primaryKey(),
      dateKey: varchar("dateKey", { length: 10 }).notNull(),
      taskId: varchar("taskId", { length: 128 }).notNull(),
      done: boolean("done").default(false).notNull(),
      help: boolean("help").default(false).notNull(),
      note: varchar("note", { length: 1024 }).notNull().default(""),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    }, (table) => ({
      dateKeyTaskIdIdx: uniqueIndex("task_states_date_task_unique").on(table.dateKey, table.taskId)
    }));
    storeCheckStates = pgTable("store_check_states", {
      id: serial("id").primaryKey(),
      dateKey: varchar("dateKey", { length: 10 }).notNull(),
      checkType: varchar("checkType", { length: 32 }).notNull(),
      checkedStores: jsonb("checkedStores").notNull().$type().default([]),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    }, (table) => ({
      dateKeyCheckTypeIdx: uniqueIndex("store_check_states_date_type_unique").on(table.dateKey, table.checkType)
    }));
    individualHandovers = pgTable("individual_handovers", {
      id: varchar("id", { length: 64 }).primaryKey(),
      dateKey: varchar("dateKey", { length: 10 }).notNull(),
      author: varchar("author", { length: 64 }).notNull().default(""),
      target: varchar("target", { length: 64 }).notNull().default(""),
      tasks: jsonb("tasks").notNull().$type().default([]),
      completed: boolean("completed").default(false).notNull(),
      important: boolean("important").default(false).notNull(),
      createdAt: timestamp("createdAt").defaultNow().notNull(),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
    customerHandovers = pgTable("customer_handovers", {
      id: varchar("id", { length: 64 }).primaryKey(),
      dateKey: varchar("dateKey", { length: 10 }).notNull(),
      customerName: varchar("customerName", { length: 128 }).notNull().default(""),
      store: varchar("store", { length: 64 }).notNull().default(""),
      content: varchar("content", { length: 2048 }).notNull().default(""),
      status: varchar("status", { length: 32 }).notNull().default("\u5BFE\u5FDC\u4E2D"),
      assignee: varchar("assignee", { length: 64 }).notNull().default(""),
      links: jsonb("links").$type(),
      dueDate: bigint("dueDate", { mode: "number" }),
      createdAt: timestamp("createdAt").defaultNow().notNull(),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
    misocaStatus = pgTable("misoca_status", {
      id: serial("id").primaryKey(),
      completedUntil: varchar("completedUntil", { length: 16 }).notNull().default(""),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
    grayCellStatus = pgTable("gray_cell_status", {
      id: serial("id").primaryKey(),
      confirmedUntil: varchar("confirmedUntil", { length: 16 }).notNull().default(""),
      updatedBy: varchar("updatedBy", { length: 64 }).notNull().default(""),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
    storesShiftStatus = pgTable("stores_shift_status", {
      id: serial("id").primaryKey(),
      confirmedUntil: varchar("confirmedUntil", { length: 16 }).notNull().default(""),
      updatedBy: varchar("updatedBy", { length: 64 }).notNull().default(""),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
    taskCategories = pgTable("task_categories", {
      id: serial("id").primaryKey(),
      name: varchar("name", { length: 128 }).notNull(),
      sortOrder: integer("sortOrder").notNull().default(0),
      isActive: boolean("isActive").notNull().default(true),
      createdAt: timestamp("createdAt").defaultNow().notNull(),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
    taskDefinitions = pgTable("task_definitions", {
      id: serial("id").primaryKey(),
      categoryId: integer("categoryId").notNull(),
      label: varchar("label", { length: 512 }).notNull(),
      defaultPlanned: varchar("defaultPlanned", { length: 64 }).notNull().default("\u5F53\u65E5\u4E8B\u52D9\u62C5\u5F53"),
      deadline: varchar("deadline", { length: 64 }).notNull().default(""),
      sortOrder: integer("sortOrder").notNull().default(0),
      isActive: boolean("isActive").notNull().default(true),
      legacyId: varchar("legacyId", { length: 128 }),
      // 既存BASE_TASKS文字列IDとの互換性維持用
      showOnDays: varchar("showOnDays", { length: 128 }).notNull().default(""),
      // 表示日制限（例: "15,30" = 毎月15日・30日のみ。空文字列 = 常時表示）
      createdAt: timestamp("createdAt").defaultNow().notNull(),
      updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
    });
  }
});

// server/vercelTrpcHandler.ts
import { nodeHTTPRequestHandler } from "@trpc/server/adapters/node-http";

// shared/const.ts
var COOKIE_NAME = "app_session_id";
var ONE_YEAR_MS = 1e3 * 60 * 60 * 24 * 365;
var AXIOS_TIMEOUT_MS = 3e4;
var UNAUTHED_ERR_MSG = "Please login (10001)";
var NOT_ADMIN_ERR_MSG = "You do not have required permission (10002)";

// server/_core/cookies.ts
function isSecureRequest(req) {
  if (req.protocol === "https") return true;
  const forwardedProto = req.headers["x-forwarded-proto"];
  if (!forwardedProto) return false;
  const protoList = Array.isArray(forwardedProto) ? forwardedProto : forwardedProto.split(",");
  return protoList.some((proto) => proto.trim().toLowerCase() === "https");
}
function getSessionCookieOptions(req) {
  return {
    httpOnly: true,
    path: "/",
    sameSite: "none",
    secure: isSecureRequest(req)
  };
}

// server/_core/systemRouter.ts
import { z } from "zod";

// server/_core/notification.ts
import { TRPCError } from "@trpc/server";

// server/_core/env.ts
var ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? ""
};

// server/_core/notification.ts
var TITLE_MAX_LENGTH = 1200;
var CONTENT_MAX_LENGTH = 2e4;
var trimValue = (value) => value.trim();
var isNonEmptyString = (value) => typeof value === "string" && value.trim().length > 0;
var buildEndpointUrl = (baseUrl) => {
  const normalizedBase = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return new URL(
    "webdevtoken.v1.WebDevService/SendNotification",
    normalizedBase
  ).toString();
};
var validatePayload = (input) => {
  if (!isNonEmptyString(input.title)) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "Notification title is required."
    });
  }
  if (!isNonEmptyString(input.content)) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "Notification content is required."
    });
  }
  const title = trimValue(input.title);
  const content = trimValue(input.content);
  if (title.length > TITLE_MAX_LENGTH) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: `Notification title must be at most ${TITLE_MAX_LENGTH} characters.`
    });
  }
  if (content.length > CONTENT_MAX_LENGTH) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: `Notification content must be at most ${CONTENT_MAX_LENGTH} characters.`
    });
  }
  return { title, content };
};
async function notifyOwner(payload) {
  const { title, content } = validatePayload(payload);
  if (!ENV.forgeApiUrl) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Notification service URL is not configured."
    });
  }
  if (!ENV.forgeApiKey) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Notification service API key is not configured."
    });
  }
  const endpoint = buildEndpointUrl(ENV.forgeApiUrl);
  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        accept: "application/json",
        authorization: `Bearer ${ENV.forgeApiKey}`,
        "content-type": "application/json",
        "connect-protocol-version": "1"
      },
      body: JSON.stringify({ title, content })
    });
    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      console.warn(
        `[Notification] Failed to notify owner (${response.status} ${response.statusText})${detail ? `: ${detail}` : ""}`
      );
      return false;
    }
    return true;
  } catch (error) {
    console.warn("[Notification] Error calling notification service:", error);
    return false;
  }
}

// server/_core/trpc.ts
import { initTRPC, TRPCError as TRPCError2 } from "@trpc/server";
import superjson from "superjson";
var t = initTRPC.context().create({
  transformer: superjson
});
var router = t.router;
var publicProcedure = t.procedure;
var requireUser = t.middleware(async (opts) => {
  const { ctx, next } = opts;
  if (!ctx.user) {
    throw new TRPCError2({ code: "UNAUTHORIZED", message: UNAUTHED_ERR_MSG });
  }
  return next({
    ctx: {
      ...ctx,
      user: ctx.user
    }
  });
});
var protectedProcedure = t.procedure.use(requireUser);
var adminProcedure = t.procedure.use(
  t.middleware(async (opts) => {
    const { ctx, next } = opts;
    if (!ctx.user || ctx.user.role !== "admin") {
      throw new TRPCError2({ code: "FORBIDDEN", message: NOT_ADMIN_ERR_MSG });
    }
    return next({
      ctx: {
        ...ctx,
        user: ctx.user
      }
    });
  })
);

// server/_core/systemRouter.ts
var systemRouter = router({
  health: publicProcedure.input(
    z.object({
      timestamp: z.number().min(0, "timestamp cannot be negative")
    })
  ).query(() => ({
    ok: true
  })),
  notifyOwner: adminProcedure.input(
    z.object({
      title: z.string().min(1, "title is required"),
      content: z.string().min(1, "content is required")
    })
  ).mutation(async ({ input }) => {
    const delivered = await notifyOwner(input);
    return {
      success: delivered
    };
  })
});

// server/taskRouter.ts
init_schema();
import { and as and2, eq as eq2, gte as gte2, lte } from "drizzle-orm";
import { z as z2 } from "zod";

// server/db.ts
init_schema();
import { and, eq, gte, ne } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
var _db = null;
var _client = null;
async function getDb() {
  if (!_db && process.env.DATABASE_URL) {
    try {
      _client = postgres(process.env.DATABASE_URL, {
        max: 5,
        prepare: false
      });
      _db = drizzle(_client);
    } catch (error) {
      console.warn("[Database] Failed to connect:", error);
      _db = null;
      _client = null;
    }
  }
  return _db;
}
async function upsertUser(user) {
  if (!user.openId) {
    throw new Error("User openId is required for upsert");
  }
  const db = await getDb();
  if (!db) {
    console.warn("[Database] Cannot upsert user: database not available");
    return;
  }
  try {
    const values = {
      openId: user.openId
    };
    const updateSet = {};
    const textFields = ["name", "email", "loginMethod"];
    const assignNullable = (field) => {
      const value = user[field];
      if (value === void 0) return;
      const normalized = value ?? null;
      values[field] = normalized;
      updateSet[field] = normalized;
    };
    textFields.forEach(assignNullable);
    if (user.lastSignedIn !== void 0) {
      values.lastSignedIn = user.lastSignedIn;
      updateSet.lastSignedIn = user.lastSignedIn;
    }
    if (user.role !== void 0) {
      values.role = user.role;
      updateSet.role = user.role;
    } else if (user.openId === ENV.ownerOpenId) {
      values.role = "admin";
      updateSet.role = "admin";
    }
    if (!values.lastSignedIn) {
      values.lastSignedIn = /* @__PURE__ */ new Date();
    }
    if (Object.keys(updateSet).length === 0) {
      updateSet.lastSignedIn = /* @__PURE__ */ new Date();
    }
    await db.insert(users).values(values).onConflictDoUpdate({
      target: users.openId,
      set: updateSet
    });
  } catch (error) {
    console.error("[Database] Failed to upsert user:", error);
    throw error;
  }
}
async function getUserByOpenId(openId) {
  const db = await getDb();
  if (!db) {
    console.warn("[Database] Cannot get user: database not available");
    return void 0;
  }
  const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1);
  return result.length > 0 ? result[0] : void 0;
}
async function cleanupOldDateKeyRecords() {
  const db = await getDb();
  if (!db) return;
  const cutoff = /* @__PURE__ */ new Date();
  cutoff.setDate(cutoff.getDate() - 3);
  const cutoffKey = cutoff.toISOString().slice(0, 10);
  const now = /* @__PURE__ */ new Date();
  const monthStart = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
  try {
    const { storeCheckStates: storeCheckStates2 } = await Promise.resolve().then(() => (init_schema(), schema_exports));
    const { lt: lt3 } = await import("drizzle-orm");
    const showOnDaysTasks = await db.select({ id: taskDefinitions.id }).from(taskDefinitions).where(and(eq(taskDefinitions.isActive, true), gte(taskDefinitions.showOnDays, "1")));
    const showOnDaysTaskIds = showOnDaysTasks.map((t2) => `def-${t2.id}`);
    await db.delete(taskStates).where(
      and(
        lt3(taskStates.dateKey, cutoffKey),
        // showOnDaysタスクの当月レコードは除外（保護）
        lt3(taskStates.dateKey, monthStart)
      )
    );
    if (showOnDaysTaskIds.length > 0) {
      for (const taskId of showOnDaysTaskIds) {
        await db.delete(taskStates).where(
          and(
            eq(taskStates.taskId, taskId),
            lt3(taskStates.dateKey, monthStart),
            ne(taskStates.done, true)
          )
        );
      }
    }
    await db.delete(storeCheckStates2).where(lt3(storeCheckStates2.dateKey, cutoffKey));
    console.log(`[Cleanup] Deleted records older than ${cutoffKey}`);
  } catch (err) {
    console.warn("[Cleanup] Failed to delete old records:", err);
  }
}

// server/taskRouter.ts
var taskStatesRouter = router({
  // Get all task states for a date
  getByDate: publicProcedure.input(z2.object({ dateKey: z2.string() })).query(async ({ input }) => {
    const db = await getDb();
    if (!db) return [];
    cleanupOldDateKeyRecords().catch(() => {
    });
    return db.select().from(taskStates).where(eq2(taskStates.dateKey, input.dateKey));
  }),
  // Get task states for a date, with monthly persistence for showOnDays tasks
  // showOnDays設定タスクは当月中に完了済みであれば、今日のdateKeyで未完了でも完了として返す
  getByDateWithMonthly: publicProcedure.input(z2.object({ dateKey: z2.string() })).query(async ({ input }) => {
    const db = await getDb();
    if (!db) return [];
    cleanupOldDateKeyRecords().catch(() => {
    });
    const todayStates = await db.select().from(taskStates).where(eq2(taskStates.dateKey, input.dateKey));
    const showOnDaysTasks = await db.select({ id: taskDefinitions.id }).from(taskDefinitions).where(and2(eq2(taskDefinitions.isActive, true), gte2(taskDefinitions.showOnDays, "1")));
    if (showOnDaysTasks.length === 0) return todayStates;
    const showOnDaysTaskIds = new Set(showOnDaysTasks.map((t2) => `def-${t2.id}`));
    const monthStart = input.dateKey.slice(0, 7) + "-01";
    const monthlyStates = await db.select().from(taskStates).where(and2(gte2(taskStates.dateKey, monthStart), lte(taskStates.dateKey, input.dateKey)));
    const todayStateMap = new Map(todayStates.map((s) => [s.taskId, s]));
    const result = todayStates.filter((s) => !showOnDaysTaskIds.has(s.taskId));
    for (const taskId of Array.from(showOnDaysTaskIds)) {
      const todayState = todayStateMap.get(taskId);
      const monthlyCompleted = monthlyStates.filter((s) => s.taskId === taskId && s.done).sort((a, b) => b.dateKey.localeCompare(a.dateKey));
      if (monthlyCompleted.length > 0 && (!todayState || !todayState.done)) {
        const original = monthlyCompleted[0];
        const completedDateTag = `__completedDate:${original.dateKey}`;
        const existingNote = original.note ?? "";
        const noteWithDate = existingNote.includes("__completedDate:") ? existingNote : existingNote ? `${existingNote}
${completedDateTag}` : completedDateTag;
        result.push({
          ...original,
          dateKey: input.dateKey,
          note: noteWithDate
        });
      } else if (todayState) {
        const todayNote = todayState.note ?? "";
        const hasCompletedDateTag = todayNote.includes("__completedDate:");
        const monthlyCompletedWithTag = monthlyCompleted.filter((s) => s.note?.includes("__completedDate:"));
        if (!hasCompletedDateTag && monthlyCompletedWithTag.length > 0) {
          const original = monthlyCompletedWithTag[0];
          const completedDateTag = `__completedDate:${original.dateKey}`;
          const originalNote = original.note ?? "";
          const completedByMatch = originalNote.match(/__completedBy:([^\n]+)/);
          const completedByTag = completedByMatch ? `
__completedBy:${completedByMatch[1].trim()}` : "";
          const cleanTodayNote = todayNote.replace(/\n?__completedDate:\d{4}-\d{2}-\d{2}/g, "").replace(/\n?__completedBy:[^\n]+/g, "").trim();
          const noteWithTags = cleanTodayNote ? `${cleanTodayNote}
${completedDateTag}${completedByTag}` : `${completedDateTag}${completedByTag}`;
          result.push({ ...todayState, note: noteWithTags });
        } else {
          result.push(todayState);
        }
      }
    }
    return result;
  }),
  // Upsert a task state
  upsert: publicProcedure.input(z2.object({ dateKey: z2.string(), taskId: z2.string(), done: z2.boolean(), help: z2.boolean().default(false), note: z2.string().default("") })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    await db.insert(taskStates).values({ dateKey: input.dateKey, taskId: input.taskId, done: input.done, help: input.help, note: input.note }).onConflictDoUpdate({
      target: [taskStates.dateKey, taskStates.taskId],
      set: { done: input.done, help: input.help, note: input.note }
    });
  }),
  // Bulk upsert task states
  bulkUpsert: publicProcedure.input(z2.array(z2.object({ dateKey: z2.string(), taskId: z2.string(), done: z2.boolean(), help: z2.boolean().default(false), note: z2.string().default("") }))).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db || input.length === 0) return;
    for (const item of input) {
      await db.insert(taskStates).values({ dateKey: item.dateKey, taskId: item.taskId, done: item.done, help: item.help, note: item.note }).onConflictDoUpdate({
        target: [taskStates.dateKey, taskStates.taskId],
        set: { done: item.done, help: item.help, note: item.note }
      });
    }
  })
});
var storeCheckRouter = router({
  getByDate: publicProcedure.input(z2.object({ dateKey: z2.string() })).query(async ({ input }) => {
    const db = await getDb();
    if (!db) return [];
    return db.select().from(storeCheckStates).where(eq2(storeCheckStates.dateKey, input.dateKey));
  }),
  upsert: publicProcedure.input(z2.object({ dateKey: z2.string(), checkType: z2.string(), checkedStores: z2.array(z2.string()) })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    await db.insert(storeCheckStates).values({ dateKey: input.dateKey, checkType: input.checkType, checkedStores: input.checkedStores }).onConflictDoUpdate({
      target: [storeCheckStates.dateKey, storeCheckStates.checkType],
      set: { checkedStores: input.checkedStores }
    });
  })
});
var individualHandoverRouter = router({
  // Get all incomplete + today's records
  getActive: publicProcedure.input(z2.object({ dateKey: z2.string() })).query(async ({ input }) => {
    const db = await getDb();
    if (!db) return [];
    const all = await db.select().from(individualHandovers).where(eq2(individualHandovers.completed, false));
    return all;
  }),
  upsert: publicProcedure.input(z2.object({
    id: z2.string(),
    dateKey: z2.string(),
    author: z2.string(),
    target: z2.string(),
    tasks: z2.array(z2.object({
      id: z2.string(),
      content: z2.string(),
      done: z2.boolean(),
      deadline: z2.string().optional()
    })),
    completed: z2.boolean(),
    important: z2.boolean().optional().default(false)
  })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    await db.insert(individualHandovers).values({ ...input, important: input.important ?? false }).onConflictDoUpdate({
      target: individualHandovers.id,
      set: { author: input.author, target: input.target, tasks: input.tasks, completed: input.completed, important: input.important ?? false }
    });
  }),
  delete: publicProcedure.input(z2.object({ id: z2.string() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    await db.delete(individualHandovers).where(eq2(individualHandovers.id, input.id));
  })
});
var customerHandoverRouter = router({
  getActive: publicProcedure.query(async () => {
    const db = await getDb();
    if (!db) return [];
    await db.delete(customerHandovers).where(eq2(customerHandovers.status, "\u5B8C\u4E86"));
    return db.select().from(customerHandovers);
  }),
  upsert: publicProcedure.input(z2.object({
    id: z2.string(),
    dateKey: z2.string(),
    customerName: z2.string(),
    store: z2.string(),
    content: z2.string(),
    status: z2.string(),
    assignee: z2.string(),
    links: z2.array(z2.string()).max(4).optional(),
    dueDate: z2.number().nullable().optional()
  })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    if (input.status === "\u5B8C\u4E86") {
      await db.delete(customerHandovers).where(eq2(customerHandovers.id, input.id));
      return;
    }
    const links = input.links ?? [];
    const dueDate = input.dueDate ?? null;
    await db.insert(customerHandovers).values({ ...input, links, dueDate }).onConflictDoUpdate({
      target: customerHandovers.id,
      set: { customerName: input.customerName, store: input.store, content: input.content, status: input.status, assignee: input.assignee, links, dueDate }
    });
  }),
  delete: publicProcedure.input(z2.object({ id: z2.string() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    await db.delete(customerHandovers).where(eq2(customerHandovers.id, input.id));
  })
});
var misocaRouter = router({
  get: publicProcedure.query(async () => {
    const db = await getDb();
    if (!db) return null;
    const result = await db.select().from(misocaStatus).limit(1);
    return result[0] ?? null;
  }),
  upsert: publicProcedure.input(z2.object({ completedUntil: z2.string() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    const existing = await db.select().from(misocaStatus).limit(1);
    if (existing.length > 0) {
      await db.update(misocaStatus).set({ completedUntil: input.completedUntil });
    } else {
      await db.insert(misocaStatus).values({ completedUntil: input.completedUntil });
    }
  })
});
var grayCellRouter = router({
  get: publicProcedure.query(async () => {
    const db = await getDb();
    if (!db) return null;
    const result = await db.select().from(grayCellStatus).limit(1);
    return result[0] ?? null;
  }),
  upsert: publicProcedure.input(z2.object({ confirmedUntil: z2.string(), updatedBy: z2.string().default("") })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    const existing = await db.select().from(grayCellStatus).limit(1);
    if (existing.length > 0) {
      await db.update(grayCellStatus).set({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy });
    } else {
      await db.insert(grayCellStatus).values({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy });
    }
  })
});
var storesShiftRouter = router({
  get: publicProcedure.query(async () => {
    const db = await getDb();
    if (!db) return null;
    const result = await db.select().from(storesShiftStatus).limit(1);
    return result[0] ?? null;
  }),
  upsert: publicProcedure.input(z2.object({ confirmedUntil: z2.string(), updatedBy: z2.string().default("") })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) return;
    const existing = await db.select().from(storesShiftStatus).limit(1);
    if (existing.length > 0) {
      await db.update(storesShiftStatus).set({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy });
    } else {
      await db.insert(storesShiftStatus).values({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy });
    }
  })
});
var taskRouter = router({
  taskStates: taskStatesRouter,
  storeCheck: storeCheckRouter,
  individualHandover: individualHandoverRouter,
  customerHandover: customerHandoverRouter,
  misoca: misocaRouter,
  grayCell: grayCellRouter,
  storesShift: storesShiftRouter
});

// server/taskDefinitionRouter.ts
import { z as z3 } from "zod";
init_schema();
import { eq as eq3, asc, and as and3 } from "drizzle-orm";
var taskDefinitionRouter = router({
  // カテゴリ一覧＋各カテゴリのタスク定義を取得
  getAll: publicProcedure.query(async () => {
    const db = await getDb();
    if (!db) return [];
    const categories = await db.select().from(taskCategories).where(eq3(taskCategories.isActive, true)).orderBy(asc(taskCategories.sortOrder));
    const definitions = await db.select().from(taskDefinitions).where(eq3(taskDefinitions.isActive, true)).orderBy(asc(taskDefinitions.sortOrder));
    return categories.map((cat) => ({
      ...cat,
      tasks: definitions.filter((d) => d.categoryId === cat.id)
    }));
  }),
  // ─── カテゴリ管理 ────────────────────────────────────────────────────────
  // カテゴリ追加
  addCategory: publicProcedure.input(
    z3.object({
      name: z3.string().min(1).max(128)
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    const existing = await db.select().from(taskCategories).where(eq3(taskCategories.isActive, true)).orderBy(asc(taskCategories.sortOrder));
    const maxSort = existing.length > 0 ? existing[existing.length - 1].sortOrder + 1 : 0;
    const [result] = await db.insert(taskCategories).values({
      name: input.name,
      sortOrder: maxSort,
      isActive: true
    }).returning({ id: taskCategories.id });
    return { id: result.id };
  }),
  // カテゴリ名変更
  updateCategory: publicProcedure.input(
    z3.object({
      id: z3.number(),
      name: z3.string().min(1).max(128)
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await db.update(taskCategories).set({ name: input.name }).where(eq3(taskCategories.id, input.id));
    return { success: true };
  }),
  // カテゴリ削除（配下のタスクも論理削除）
  deleteCategory: publicProcedure.input(z3.object({ id: z3.number() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await db.update(taskDefinitions).set({ isActive: false }).where(eq3(taskDefinitions.categoryId, input.id));
    await db.update(taskCategories).set({ isActive: false }).where(eq3(taskCategories.id, input.id));
    return { success: true };
  }),
  // カテゴリ並び替え（sortOrderを一括更新）
  reorderCategories: publicProcedure.input(
    z3.object({
      categories: z3.array(z3.object({ id: z3.number(), sortOrder: z3.number() }))
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await Promise.all(
      input.categories.map(
        ({ id, sortOrder }) => db.update(taskCategories).set({ sortOrder }).where(eq3(taskCategories.id, id))
      )
    );
    return { success: true };
  }),
  // ─── タスク管理 ────────────────────────────────────────────────────────
  // タスク追加
  addTask: publicProcedure.input(
    z3.object({
      categoryId: z3.number(),
      label: z3.string().min(1).max(512),
      defaultPlanned: z3.string().max(64).default("\u5F53\u65E5\u4E8B\u52D9\u62C5\u5F53"),
      deadline: z3.string().max(64).default("")
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    const existing = await db.select().from(taskDefinitions).where(
      and3(
        eq3(taskDefinitions.categoryId, input.categoryId),
        eq3(taskDefinitions.isActive, true)
      )
    ).orderBy(asc(taskDefinitions.sortOrder));
    const maxSort = existing.length > 0 ? existing[existing.length - 1].sortOrder + 1 : 0;
    const [result] = await db.insert(taskDefinitions).values({
      categoryId: input.categoryId,
      label: input.label,
      defaultPlanned: input.defaultPlanned,
      deadline: input.deadline,
      sortOrder: maxSort,
      isActive: true
    }).returning({ id: taskDefinitions.id });
    return { id: result.id };
  }),
  // タスク編集
  updateTask: publicProcedure.input(
    z3.object({
      id: z3.number(),
      label: z3.string().min(1).max(512).optional(),
      defaultPlanned: z3.string().max(64).optional(),
      deadline: z3.string().max(64).optional(),
      showOnDays: z3.string().max(128).optional()
      // 例: "15,30" = 毎月15日・30日のみ。空文字列 = 常時表示
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    const { id, ...updates } = input;
    await db.update(taskDefinitions).set(updates).where(eq3(taskDefinitions.id, id));
    return { success: true };
  }),
  // タスク論理削除
  deleteTask: publicProcedure.input(z3.object({ id: z3.number() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await db.update(taskDefinitions).set({ isActive: false }).where(eq3(taskDefinitions.id, input.id));
    return { success: true };
  }),
  // タスク並び替え（同カテゴリ内のsortOrderを一括更新）
  reorderTasks: publicProcedure.input(
    z3.object({
      // [{id, sortOrder}] の配列
      tasks: z3.array(z3.object({ id: z3.number(), sortOrder: z3.number() }))
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await Promise.all(
      input.tasks.map(
        ({ id, sortOrder }) => db.update(taskDefinitions).set({ sortOrder }).where(eq3(taskDefinitions.id, id))
      )
    );
    return { success: true };
  })
});

// server/routers.ts
var appRouter = router({
  // if you need to use socket.io, read and register route in server/_core/index.ts, all api should start with '/api/' so that the gateway can route correctly
  system: systemRouter,
  auth: router({
    me: publicProcedure.query((opts) => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return {
        success: true
      };
    })
  }),
  task: taskRouter,
  taskDefinition: taskDefinitionRouter
  // TODO: add feature routers here, e.g.
  // todo: router({
  //   list: protectedProcedure.query(({ ctx }) =>
  //     db.getUserTodos(ctx.user.id)
  //   ),
  // }),
});

// shared/_core/errors.ts
var HttpError = class extends Error {
  constructor(statusCode, message) {
    super(message);
    this.statusCode = statusCode;
    this.name = "HttpError";
  }
};
var ForbiddenError = (msg) => new HttpError(403, msg);

// server/_core/sdk.ts
import axios from "axios";
import { parse as parseCookieHeader } from "cookie";
import { SignJWT, jwtVerify } from "jose";
var isNonEmptyString2 = (value) => typeof value === "string" && value.length > 0;
var EXCHANGE_TOKEN_PATH = `/webdev.v1.WebDevAuthPublicService/ExchangeToken`;
var GET_USER_INFO_PATH = `/webdev.v1.WebDevAuthPublicService/GetUserInfo`;
var GET_USER_INFO_WITH_JWT_PATH = `/webdev.v1.WebDevAuthPublicService/GetUserInfoWithJwt`;
var OAuthService = class {
  constructor(client) {
    this.client = client;
    console.log("[OAuth] Initialized with baseURL:", ENV.oAuthServerUrl);
    if (!ENV.oAuthServerUrl) {
      console.error(
        "[OAuth] ERROR: OAUTH_SERVER_URL is not configured! Set OAUTH_SERVER_URL environment variable."
      );
    }
  }
  decodeState(state) {
    const redirectUri = atob(state);
    return redirectUri;
  }
  async getTokenByCode(code, state) {
    const payload = {
      clientId: ENV.appId,
      grantType: "authorization_code",
      code,
      redirectUri: this.decodeState(state)
    };
    const { data } = await this.client.post(
      EXCHANGE_TOKEN_PATH,
      payload
    );
    return data;
  }
  async getUserInfoByToken(token) {
    const { data } = await this.client.post(
      GET_USER_INFO_PATH,
      {
        accessToken: token.accessToken
      }
    );
    return data;
  }
};
var createOAuthHttpClient = () => axios.create({
  baseURL: ENV.oAuthServerUrl,
  timeout: AXIOS_TIMEOUT_MS
});
var SDKServer = class {
  client;
  oauthService;
  constructor(client = createOAuthHttpClient()) {
    this.client = client;
    this.oauthService = new OAuthService(this.client);
  }
  deriveLoginMethod(platforms, fallback) {
    if (fallback && fallback.length > 0) return fallback;
    if (!Array.isArray(platforms) || platforms.length === 0) return null;
    const set = new Set(
      platforms.filter((p) => typeof p === "string")
    );
    if (set.has("REGISTERED_PLATFORM_EMAIL")) return "email";
    if (set.has("REGISTERED_PLATFORM_GOOGLE")) return "google";
    if (set.has("REGISTERED_PLATFORM_APPLE")) return "apple";
    if (set.has("REGISTERED_PLATFORM_MICROSOFT") || set.has("REGISTERED_PLATFORM_AZURE"))
      return "microsoft";
    if (set.has("REGISTERED_PLATFORM_GITHUB")) return "github";
    const first = Array.from(set)[0];
    return first ? first.toLowerCase() : null;
  }
  /**
   * Exchange OAuth authorization code for access token
   * @example
   * const tokenResponse = await sdk.exchangeCodeForToken(code, state);
   */
  async exchangeCodeForToken(code, state) {
    return this.oauthService.getTokenByCode(code, state);
  }
  /**
   * Get user information using access token
   * @example
   * const userInfo = await sdk.getUserInfo(tokenResponse.accessToken);
   */
  async getUserInfo(accessToken) {
    const data = await this.oauthService.getUserInfoByToken({
      accessToken
    });
    const loginMethod = this.deriveLoginMethod(
      data?.platforms,
      data?.platform ?? data.platform ?? null
    );
    return {
      ...data,
      platform: loginMethod,
      loginMethod
    };
  }
  parseCookies(cookieHeader) {
    if (!cookieHeader) {
      return /* @__PURE__ */ new Map();
    }
    const parsed = parseCookieHeader(cookieHeader);
    return new Map(Object.entries(parsed));
  }
  getSessionSecret() {
    const secret = ENV.cookieSecret;
    return new TextEncoder().encode(secret);
  }
  /**
   * Create a session token for a Manus user openId
   * @example
   * const sessionToken = await sdk.createSessionToken(userInfo.openId);
   */
  async createSessionToken(openId, options = {}) {
    return this.signSession(
      {
        openId,
        appId: ENV.appId,
        name: options.name || ""
      },
      options
    );
  }
  async signSession(payload, options = {}) {
    const issuedAt = Date.now();
    const expiresInMs = options.expiresInMs ?? ONE_YEAR_MS;
    const expirationSeconds = Math.floor((issuedAt + expiresInMs) / 1e3);
    const secretKey = this.getSessionSecret();
    return new SignJWT({
      openId: payload.openId,
      appId: payload.appId,
      name: payload.name
    }).setProtectedHeader({ alg: "HS256", typ: "JWT" }).setExpirationTime(expirationSeconds).sign(secretKey);
  }
  async verifySession(cookieValue) {
    if (!cookieValue) {
      console.warn("[Auth] Missing session cookie");
      return null;
    }
    try {
      const secretKey = this.getSessionSecret();
      const { payload } = await jwtVerify(cookieValue, secretKey, {
        algorithms: ["HS256"]
      });
      const { openId, appId, name } = payload;
      if (!isNonEmptyString2(openId) || !isNonEmptyString2(appId) || !isNonEmptyString2(name)) {
        console.warn("[Auth] Session payload missing required fields");
        return null;
      }
      return {
        openId,
        appId,
        name
      };
    } catch (error) {
      console.warn("[Auth] Session verification failed", String(error));
      return null;
    }
  }
  async getUserInfoWithJwt(jwtToken) {
    const payload = {
      jwtToken,
      projectId: ENV.appId
    };
    const { data } = await this.client.post(
      GET_USER_INFO_WITH_JWT_PATH,
      payload
    );
    const loginMethod = this.deriveLoginMethod(
      data?.platforms,
      data?.platform ?? data.platform ?? null
    );
    return {
      ...data,
      platform: loginMethod,
      loginMethod
    };
  }
  async authenticateRequest(req) {
    const cookies = this.parseCookies(req.headers.cookie);
    const sessionCookie = cookies.get(COOKIE_NAME);
    const session = await this.verifySession(sessionCookie);
    if (!session) {
      throw ForbiddenError("Invalid session cookie");
    }
    const sessionUserId = session.openId;
    const signedInAt = /* @__PURE__ */ new Date();
    let user = await getUserByOpenId(sessionUserId);
    if (!user) {
      try {
        const userInfo = await this.getUserInfoWithJwt(sessionCookie ?? "");
        await upsertUser({
          openId: userInfo.openId,
          name: userInfo.name || null,
          email: userInfo.email ?? null,
          loginMethod: userInfo.loginMethod ?? userInfo.platform ?? null,
          lastSignedIn: signedInAt
        });
        user = await getUserByOpenId(userInfo.openId);
      } catch (error) {
        console.error("[Auth] Failed to sync user from OAuth:", error);
        throw ForbiddenError("Failed to sync user info");
      }
    }
    if (!user) {
      throw ForbiddenError("User not found");
    }
    await upsertUser({
      openId: user.openId,
      lastSignedIn: signedInAt
    });
    return user;
  }
};
var sdk = new SDKServer();

// server/vercelTrpcHandler.ts
var config = {
  api: {
    bodyParser: false
  }
};
function appendSetCookie(res, cookie) {
  const current = res.getHeader("Set-Cookie");
  if (!current) {
    res.setHeader("Set-Cookie", cookie);
    return;
  }
  const values = Array.isArray(current) ? current : [String(current)];
  res.setHeader("Set-Cookie", [...values, cookie]);
}
function serializeClearedCookie(name, options) {
  const parts = [
    `${encodeURIComponent(name)}=`,
    "Expires=Thu, 01 Jan 1970 00:00:00 GMT",
    "Max-Age=0"
  ];
  if (options.domain) parts.push(`Domain=${options.domain}`);
  if (options.path) parts.push(`Path=${options.path}`);
  if (options.httpOnly) parts.push("HttpOnly");
  if (options.secure) parts.push("Secure");
  if (options.sameSite) {
    const sameSite = options.sameSite === true ? "Strict" : options.sameSite;
    parts.push(`SameSite=${sameSite.charAt(0).toUpperCase()}${sameSite.slice(1)}`);
  }
  return parts.join("; ");
}
function withExpressCookieCompat(res) {
  res.clearCookie = (name, options = {}) => {
    appendSetCookie(
      res,
      serializeClearedCookie(name, {
        domain: options.domain,
        httpOnly: options.httpOnly,
        path: options.path ?? "/",
        sameSite: options.sameSite,
        secure: options.secure
      })
    );
  };
  return res;
}
function getTrpcPath(req) {
  const queryPath = req.query?.trpc;
  if (Array.isArray(queryPath)) return queryPath.join("/");
  if (queryPath) return queryPath;
  const pathname = (req.url ?? "").split("?")[0] ?? "";
  return pathname.replace(/^\/api\/trpc\/?/, "");
}
async function handler(req, res) {
  const response = withExpressCookieCompat(res);
  await nodeHTTPRequestHandler({
    req,
    res: response,
    path: getTrpcPath(req),
    router: appRouter,
    createContext: async () => {
      let user = null;
      try {
        user = await sdk.authenticateRequest(req);
      } catch {
        user = null;
      }
      return {
        req,
        res: response,
        user
      };
    }
  });
}
export {
  config,
  handler as default
};
