// Generated by scripts/build-vercel-api.mjs. Do not edit by hand.

// server/vercelTrpcHandler.ts
import { nodeHTTPRequestHandler } from "@trpc/server/adapters/node-http";

// shared/const.ts
var COOKIE_NAME = "app_session_id";
var ONE_YEAR_MS = 1e3 * 60 * 60 * 24 * 365;
var UNAUTHED_ERR_MSG = "Please login (10001)";
var NOT_ADMIN_ERR_MSG = "You do not have required permission (10002)";

// server/_core/cookies.ts
function isSecureRequest(req) {
  if (req.protocol === "https") return true;
  const forwardedProto = req.headers["x-forwarded-proto"];
  if (!forwardedProto) return false;
  const protoList = Array.isArray(forwardedProto) ? forwardedProto : forwardedProto.split(",");
  return protoList.some((proto) => proto.trim().toLowerCase() === "https");
}
function getSessionCookieOptions(req) {
  return {
    httpOnly: true,
    path: "/",
    sameSite: "none",
    secure: isSecureRequest(req)
  };
}

// server/_core/systemRouter.ts
import { z } from "zod";

// server/_core/notification.ts
import { TRPCError } from "@trpc/server";

// server/_core/env.ts
var ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? ""
};

// server/_core/notification.ts
var TITLE_MAX_LENGTH = 1200;
var CONTENT_MAX_LENGTH = 2e4;
var trimValue = (value) => value.trim();
var isNonEmptyString = (value) => typeof value === "string" && value.trim().length > 0;
var buildEndpointUrl = (baseUrl) => {
  const normalizedBase = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return new URL(
    "webdevtoken.v1.WebDevService/SendNotification",
    normalizedBase
  ).toString();
};
var validatePayload = (input) => {
  if (!isNonEmptyString(input.title)) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "Notification title is required."
    });
  }
  if (!isNonEmptyString(input.content)) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "Notification content is required."
    });
  }
  const title = trimValue(input.title);
  const content = trimValue(input.content);
  if (title.length > TITLE_MAX_LENGTH) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: `Notification title must be at most ${TITLE_MAX_LENGTH} characters.`
    });
  }
  if (content.length > CONTENT_MAX_LENGTH) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: `Notification content must be at most ${CONTENT_MAX_LENGTH} characters.`
    });
  }
  return { title, content };
};
async function notifyOwner(payload) {
  const { title, content } = validatePayload(payload);
  if (!ENV.forgeApiUrl) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Notification service URL is not configured."
    });
  }
  if (!ENV.forgeApiKey) {
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "Notification service API key is not configured."
    });
  }
  const endpoint = buildEndpointUrl(ENV.forgeApiUrl);
  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        accept: "application/json",
        authorization: `Bearer ${ENV.forgeApiKey}`,
        "content-type": "application/json",
        "connect-protocol-version": "1"
      },
      body: JSON.stringify({ title, content })
    });
    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      console.warn(
        `[Notification] Failed to notify owner (${response.status} ${response.statusText})${detail ? `: ${detail}` : ""}`
      );
      return false;
    }
    return true;
  } catch (error) {
    console.warn("[Notification] Error calling notification service:", error);
    return false;
  }
}

// server/_core/trpc.ts
import { initTRPC, TRPCError as TRPCError2 } from "@trpc/server";
import superjson from "superjson";
var t = initTRPC.context().create({
  transformer: superjson
});
var router = t.router;
var publicProcedure = t.procedure;
function isApplicationLoginRequired() {
  return process.env.AUTH_REQUIRED === "true";
}
var requireUser = t.middleware(async (opts) => {
  const { ctx, next } = opts;
  if (!ctx.user) {
    throw new TRPCError2({ code: "UNAUTHORIZED", message: UNAUTHED_ERR_MSG });
  }
  return next({
    ctx: {
      ...ctx,
      user: ctx.user
    }
  });
});
var protectedProcedure = t.procedure.use(requireUser);
var adminProcedure = t.procedure.use(
  t.middleware(async (opts) => {
    const { ctx, next } = opts;
    if (!ctx.user || ctx.user.role !== "admin") {
      throw new TRPCError2({ code: "FORBIDDEN", message: NOT_ADMIN_ERR_MSG });
    }
    return next({
      ctx: {
        ...ctx,
        user: ctx.user
      }
    });
  })
);
var requireUserWhenLoginEnabled = t.middleware(async (opts) => {
  if (!isApplicationLoginRequired()) return opts.next({ ctx: opts.ctx });
  if (!opts.ctx.user) {
    throw new TRPCError2({ code: "UNAUTHORIZED", message: UNAUTHED_ERR_MSG });
  }
  return opts.next({
    ctx: {
      ...opts.ctx,
      user: opts.ctx.user
    }
  });
});
var requireAdminWhenLoginEnabled = t.middleware(async (opts) => {
  if (!isApplicationLoginRequired()) return opts.next({ ctx: opts.ctx });
  if (!opts.ctx.user || opts.ctx.user.role !== "admin") {
    throw new TRPCError2({ code: "FORBIDDEN", message: NOT_ADMIN_ERR_MSG });
  }
  return opts.next({
    ctx: {
      ...opts.ctx,
      user: opts.ctx.user
    }
  });
});
var appProcedure = t.procedure.use(requireUserWhenLoginEnabled);
var appAdminProcedure = t.procedure.use(requireAdminWhenLoginEnabled);

// server/_core/systemRouter.ts
var systemRouter = router({
  health: publicProcedure.input(
    z.object({
      timestamp: z.number().min(0, "timestamp cannot be negative")
    })
  ).query(() => ({
    ok: true
  })),
  notifyOwner: adminProcedure.input(
    z.object({
      title: z.string().min(1, "title is required"),
      content: z.string().min(1, "content is required")
    })
  ).mutation(async ({ input }) => {
    const delivered = await notifyOwner(input);
    return {
      success: delivered
    };
  })
});

// server/taskRouter.ts
import { and, eq as eq2, gte, isNull, lte, ne } from "drizzle-orm";
import { TRPCError as TRPCError3 } from "@trpc/server";
import { z as z2 } from "zod";

// drizzle/schema.ts
import {
  bigint,
  boolean,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  varchar
} from "drizzle-orm/pg-core";
var userRole = pgEnum("role", ["user", "admin"]);
var users = pgTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: serial("id").primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: userRole("role").default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date()),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull()
});
var taskStates = pgTable(
  "task_states",
  {
    id: serial("id").primaryKey(),
    dateKey: varchar("dateKey", { length: 10 }).notNull(),
    taskId: varchar("taskId", { length: 128 }).notNull(),
    done: boolean("done").default(false).notNull(),
    help: boolean("help").default(false).notNull(),
    note: varchar("note", { length: 1024 }).notNull().default(""),
    planned: varchar("planned", { length: 64 }).notNull().default(""),
    revision: integer("revision").notNull().default(1),
    updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
  },
  (table) => ({
    dateKeyTaskIdIdx: uniqueIndex("task_states_date_task_unique").on(
      table.dateKey,
      table.taskId
    )
  })
);
var storeCheckStates = pgTable(
  "store_check_states",
  {
    id: serial("id").primaryKey(),
    dateKey: varchar("dateKey", { length: 10 }).notNull(),
    checkType: varchar("checkType", { length: 32 }).notNull(),
    checkedStores: jsonb("checkedStores").notNull().$type().default([]),
    revision: integer("revision").notNull().default(1),
    updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
  },
  (table) => ({
    dateKeyCheckTypeIdx: uniqueIndex("store_check_states_date_type_unique").on(
      table.dateKey,
      table.checkType
    )
  })
);
var individualHandovers = pgTable("individual_handovers", {
  id: varchar("id", { length: 64 }).primaryKey(),
  dateKey: varchar("dateKey", { length: 10 }).notNull(),
  author: varchar("author", { length: 64 }).notNull().default(""),
  target: varchar("target", { length: 64 }).notNull().default(""),
  tasks: jsonb("tasks").notNull().$type().default([]),
  completed: boolean("completed").default(false).notNull(),
  completedAt: timestamp("completedAt"),
  deletedAt: timestamp("deletedAt"),
  important: boolean("important").default(false).notNull(),
  updatedBy: varchar("updatedBy", { length: 64 }).notNull().default(""),
  revision: integer("revision").notNull().default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});
var customerHandovers = pgTable("customer_handovers", {
  id: varchar("id", { length: 64 }).primaryKey(),
  dateKey: varchar("dateKey", { length: 10 }).notNull(),
  customerName: varchar("customerName", { length: 128 }).notNull().default(""),
  store: varchar("store", { length: 64 }).notNull().default(""),
  content: varchar("content", { length: 2048 }).notNull().default(""),
  status: varchar("status", { length: 32 }).notNull().default("\u5BFE\u5FDC\u4E2D"),
  assignee: varchar("assignee", { length: 64 }).notNull().default(""),
  links: jsonb("links").$type(),
  dueDate: bigint("dueDate", { mode: "number" }),
  callCount: integer("callCount").default(0).notNull(),
  completedAt: timestamp("completedAt"),
  deletedAt: timestamp("deletedAt"),
  updatedBy: varchar("updatedBy", { length: 64 }).notNull().default(""),
  revision: integer("revision").notNull().default(1),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});
var auditLogs = pgTable("audit_logs", {
  id: serial("id").primaryKey(),
  entityType: varchar("entityType", { length: 64 }).notNull(),
  entityId: varchar("entityId", { length: 128 }).notNull(),
  action: varchar("action", { length: 32 }).notNull(),
  before: jsonb("before").$type(),
  after: jsonb("after").$type(),
  actorId: varchar("actorId", { length: 64 }),
  requestId: varchar("requestId", { length: 128 }),
  createdAt: timestamp("createdAt").defaultNow().notNull()
});
var misocaStatus = pgTable("misoca_status", {
  id: serial("id").primaryKey(),
  completedUntil: varchar("completedUntil", { length: 16 }).notNull().default(""),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});
var grayCellStatus = pgTable("gray_cell_status", {
  id: serial("id").primaryKey(),
  confirmedUntil: varchar("confirmedUntil", { length: 16 }).notNull().default(""),
  updatedBy: varchar("updatedBy", { length: 64 }).notNull().default(""),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});
var storesShiftStatus = pgTable("stores_shift_status", {
  id: serial("id").primaryKey(),
  confirmedUntil: varchar("confirmedUntil", { length: 16 }).notNull().default(""),
  updatedBy: varchar("updatedBy", { length: 64 }).notNull().default(""),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});
var taskCategories = pgTable("task_categories", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 128 }).notNull(),
  sortOrder: integer("sortOrder").notNull().default(0),
  isActive: boolean("isActive").notNull().default(true),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});
var taskDefinitions = pgTable("task_definitions", {
  id: serial("id").primaryKey(),
  categoryId: integer("categoryId").notNull(),
  label: varchar("label", { length: 512 }).notNull(),
  defaultPlanned: varchar("defaultPlanned", { length: 64 }).notNull().default("\u5F53\u65E5\u4E8B\u52D9\u62C5\u5F53"),
  deadline: varchar("deadline", { length: 64 }).notNull().default(""),
  sortOrder: integer("sortOrder").notNull().default(0),
  isActive: boolean("isActive").notNull().default(true),
  legacyId: varchar("legacyId", { length: 128 }),
  // 既存BASE_TASKS文字列IDとの互換性維持用
  showOnDays: varchar("showOnDays", { length: 128 }).notNull().default(""),
  // 表示日制限（例: "15,30" = 毎月15日・30日のみ。空文字列 = 常時表示）
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull().$onUpdate(() => /* @__PURE__ */ new Date())
});

// server/db.ts
import { eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
var _db = null;
var _client = null;
async function getDb() {
  if (!_db && process.env.DATABASE_URL) {
    try {
      _client = postgres(process.env.DATABASE_URL, {
        max: 5,
        prepare: false
      });
      _db = drizzle(_client);
    } catch (error) {
      console.warn("[Database] Failed to connect:", error);
      _db = null;
      _client = null;
    }
  }
  return _db;
}

// server/taskRouter.ts
var expectedRevision = z2.number().int().positive().nullable().optional();
var requestIdInput = z2.string().max(128).optional();
async function requireDb() {
  const db = await getDb();
  if (!db) {
    throw new TRPCError3({
      code: "INTERNAL_SERVER_ERROR",
      message: "\u30C7\u30FC\u30BF\u30D9\u30FC\u30B9\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093\u3002\u30C7\u30FC\u30BF\u306F\u5909\u66F4\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002"
    });
  }
  return db;
}
function getAuditActor(ctx, requestId) {
  const header = ctx.req.headers?.["x-request-id"];
  const headerValue = Array.isArray(header) ? header[0] : header;
  return { actorId: ctx.user?.openId ?? "legacy-unauthenticated", requestId: requestId ?? headerValue ?? null };
}
function conflictError() {
  return new TRPCError3({
    code: "CONFLICT",
    message: "\u4ED6\u306E\u7AEF\u672B\u3067\u5148\u306B\u66F4\u65B0\u3055\u308C\u3066\u3044\u307E\u3059\u3002\u6700\u65B0\u30C7\u30FC\u30BF\u3092\u78BA\u8A8D\u3057\u3066\u304B\u3089\u518D\u8A66\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002"
  });
}
function notFoundError() {
  return new TRPCError3({ code: "NOT_FOUND", message: "\u5BFE\u8C61\u30C7\u30FC\u30BF\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002" });
}
async function writeAudit(tx, actor, entityType, entityId, action, before, after) {
  await tx.insert(auditLogs).values({
    entityType,
    entityId: String(entityId),
    action,
    before,
    after,
    actorId: actor.actorId,
    requestId: actor.requestId
  });
}
function assertExpectedRevision(currentRevision, expected) {
  if (expected == null || expected !== currentRevision) throw conflictError();
}
var taskStateInput = z2.object({
  dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  taskId: z2.string().min(1).max(128),
  done: z2.boolean(),
  help: z2.boolean().default(false),
  note: z2.string().max(1024).default(""),
  planned: z2.string().max(64).default(""),
  expectedRevision,
  requestId: requestIdInput
});
async function saveTaskState(tx, input, actor) {
  const current = await tx.select().from(taskStates).where(and(eq2(taskStates.dateKey, input.dateKey), eq2(taskStates.taskId, input.taskId))).limit(1);
  if (current.length === 0) {
    if (input.expectedRevision != null) throw conflictError();
    const [created] = await tx.insert(taskStates).values({
      dateKey: input.dateKey,
      taskId: input.taskId,
      done: input.done,
      help: input.help,
      note: input.note,
      planned: input.planned,
      revision: 1
    }).returning();
    await writeAudit(tx, actor, "task_state", `${input.dateKey}:${input.taskId}`, "create", null, created);
    return created;
  }
  const previous = current[0];
  assertExpectedRevision(previous.revision, input.expectedRevision);
  const [updated] = await tx.update(taskStates).set({
    done: input.done,
    help: input.help,
    note: input.note,
    planned: input.planned,
    revision: previous.revision + 1
  }).where(
    and(
      eq2(taskStates.dateKey, input.dateKey),
      eq2(taskStates.taskId, input.taskId),
      eq2(taskStates.revision, input.expectedRevision)
    )
  ).returning();
  if (!updated) throw conflictError();
  await writeAudit(tx, actor, "task_state", `${input.dateKey}:${input.taskId}`, "update", previous, updated);
  return updated;
}
var taskStatesRouter = router({
  getByDate: appProcedure.input(z2.object({ dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).query(async ({ input }) => {
    const db = await requireDb();
    return db.select().from(taskStates).where(eq2(taskStates.dateKey, input.dateKey));
  }),
  getByDateWithMonthly: appProcedure.input(z2.object({ dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).query(async ({ input }) => {
    const db = await requireDb();
    const todayStates = await db.select().from(taskStates).where(eq2(taskStates.dateKey, input.dateKey));
    const showOnDaysTasks = await db.select({ id: taskDefinitions.id }).from(taskDefinitions).where(and(eq2(taskDefinitions.isActive, true), gte(taskDefinitions.showOnDays, "1")));
    if (showOnDaysTasks.length === 0) return todayStates;
    const showOnDaysTaskIds = new Set(showOnDaysTasks.map((t2) => `def-${t2.id}`));
    const monthStart = `${input.dateKey.slice(0, 7)}-01`;
    const monthlyStates = await db.select().from(taskStates).where(and(gte(taskStates.dateKey, monthStart), lte(taskStates.dateKey, input.dateKey)));
    const todayStateMap = new Map(todayStates.map((s) => [s.taskId, s]));
    const result = todayStates.filter((s) => !showOnDaysTaskIds.has(s.taskId));
    for (const taskId of Array.from(showOnDaysTaskIds)) {
      const todayState = todayStateMap.get(taskId);
      const monthlyCompleted = monthlyStates.filter((s) => s.taskId === taskId && s.done).sort((a, b) => b.dateKey.localeCompare(a.dateKey));
      if (monthlyCompleted.length > 0 && (!todayState || !todayState.done)) {
        const original = monthlyCompleted[0];
        const completedDateTag = `__completedDate:${original.dateKey}`;
        const existingNote = original.note ?? "";
        result.push({
          ...original,
          dateKey: input.dateKey,
          // This row is synthesized for display. It has no current-date database
          // row, so clients must create rather than overwrite the older record.
          revision: 0,
          note: existingNote.includes("__completedDate:") ? existingNote : existingNote ? `${existingNote}
${completedDateTag}` : completedDateTag
        });
        continue;
      }
      if (!todayState) continue;
      const todayNote = todayState.note ?? "";
      const hasCompletedDateTag = todayNote.includes("__completedDate:");
      const taggedCompletion = monthlyCompleted.find((s) => s.note?.includes("__completedDate:"));
      if (!hasCompletedDateTag && taggedCompletion) {
        const completedDateTag = `__completedDate:${taggedCompletion.dateKey}`;
        const completedByMatch = (taggedCompletion.note ?? "").match(/__completedBy:([^\n]+)/);
        const completedByTag = completedByMatch ? `
__completedBy:${completedByMatch[1].trim()}` : "";
        const cleanTodayNote = todayNote.replace(/\n?__completedDate:\d{4}-\d{2}-\d{2}/g, "").replace(/\n?__completedBy:[^\n]+/g, "").trim();
        result.push({
          ...todayState,
          note: cleanTodayNote ? `${cleanTodayNote}
${completedDateTag}${completedByTag}` : `${completedDateTag}${completedByTag}`
        });
      } else {
        result.push(todayState);
      }
    }
    return result;
  }),
  upsert: appProcedure.input(taskStateInput).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return db.transaction((tx) => saveTaskState(tx, input, getAuditActor(ctx, input.requestId)));
  }),
  bulkUpsert: appProcedure.input(z2.array(taskStateInput).min(1)).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return db.transaction(async (tx) => {
      const saved = [];
      for (const item of input) {
        saved.push(await saveTaskState(tx, item, getAuditActor(ctx, item.requestId)));
      }
      return saved;
    });
  })
});
var storeCheckInput = z2.object({
  dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  checkType: z2.string().min(1).max(32),
  checkedStores: z2.array(z2.string()),
  expectedRevision,
  requestId: requestIdInput
});
async function saveStoreCheck(tx, input, actor) {
  const current = await tx.select().from(storeCheckStates).where(and(eq2(storeCheckStates.dateKey, input.dateKey), eq2(storeCheckStates.checkType, input.checkType))).limit(1);
  if (current.length === 0) {
    if (input.expectedRevision != null) throw conflictError();
    const [created] = await tx.insert(storeCheckStates).values({ dateKey: input.dateKey, checkType: input.checkType, checkedStores: input.checkedStores, revision: 1 }).returning();
    await writeAudit(tx, actor, "store_check", `${input.dateKey}:${input.checkType}`, "create", null, created);
    return created;
  }
  const previous = current[0];
  assertExpectedRevision(previous.revision, input.expectedRevision);
  const [updated] = await tx.update(storeCheckStates).set({ checkedStores: input.checkedStores, revision: previous.revision + 1 }).where(
    and(
      eq2(storeCheckStates.dateKey, input.dateKey),
      eq2(storeCheckStates.checkType, input.checkType),
      eq2(storeCheckStates.revision, input.expectedRevision)
    )
  ).returning();
  if (!updated) throw conflictError();
  await writeAudit(tx, actor, "store_check", `${input.dateKey}:${input.checkType}`, "update", previous, updated);
  return updated;
}
var storeCheckRouter = router({
  getByDate: appProcedure.input(z2.object({ dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).query(async ({ input }) => {
    const db = await requireDb();
    return db.select().from(storeCheckStates).where(eq2(storeCheckStates.dateKey, input.dateKey));
  }),
  upsert: appProcedure.input(storeCheckInput).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return db.transaction((tx) => saveStoreCheck(tx, input, getAuditActor(ctx, input.requestId)));
  }),
  bulkUpsert: appProcedure.input(z2.array(storeCheckInput).min(1)).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return db.transaction(async (tx) => {
      const saved = [];
      for (const item of input) saved.push(await saveStoreCheck(tx, item, getAuditActor(ctx, item.requestId)));
      return saved;
    });
  })
});
var individualInput = z2.object({
  id: z2.string().min(1).max(64),
  dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  author: z2.string().max(64),
  target: z2.string().max(64),
  tasks: z2.array(z2.object({ id: z2.string(), content: z2.string(), done: z2.boolean(), deadline: z2.string().optional() })),
  completed: z2.boolean(),
  important: z2.boolean().optional().default(false),
  expectedRevision,
  requestId: requestIdInput
});
var individualHandoverRouter = router({
  getActive: appProcedure.input(z2.object({ dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).query(async () => {
    const db = await requireDb();
    return db.select().from(individualHandovers).where(and(eq2(individualHandovers.completed, false), isNull(individualHandovers.deletedAt)));
  }),
  upsert: appProcedure.input(individualInput).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const current = await tx.select().from(individualHandovers).where(eq2(individualHandovers.id, input.id)).limit(1);
      const now = /* @__PURE__ */ new Date();
      if (current.length === 0) {
        if (input.expectedRevision != null) throw conflictError();
        const [created] = await tx.insert(individualHandovers).values({
          id: input.id,
          dateKey: input.dateKey,
          author: input.author,
          target: input.target,
          tasks: input.tasks,
          completed: input.completed,
          completedAt: input.completed ? now : null,
          important: input.important,
          updatedBy: actor.actorId,
          revision: 1
        }).returning();
        await writeAudit(tx, actor, "individual_handover", input.id, input.completed ? "complete" : "create", null, created);
        return created;
      }
      const previous = current[0];
      if (previous.deletedAt) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const [updated] = await tx.update(individualHandovers).set({
        author: input.author,
        target: input.target,
        tasks: input.tasks,
        completed: input.completed,
        completedAt: input.completed ? previous.completedAt ?? now : null,
        important: input.important,
        updatedBy: actor.actorId,
        revision: previous.revision + 1
      }).where(and(eq2(individualHandovers.id, input.id), eq2(individualHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "individual_handover", input.id, input.completed ? "complete" : "update", previous, updated);
      return updated;
    });
  }),
  delete: appProcedure.input(z2.object({ id: z2.string(), expectedRevision: z2.number().int().positive(), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(individualHandovers).where(eq2(individualHandovers.id, input.id)).limit(1);
      if (!previous) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const [updated] = await tx.update(individualHandovers).set({ deletedAt: /* @__PURE__ */ new Date(), updatedBy: actor.actorId, revision: previous.revision + 1 }).where(and(eq2(individualHandovers.id, input.id), eq2(individualHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "individual_handover", input.id, "soft_delete", previous, updated);
      return updated;
    });
  }),
  restore: appProcedure.input(z2.object({ id: z2.string(), expectedRevision: z2.number().int().positive(), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(individualHandovers).where(eq2(individualHandovers.id, input.id)).limit(1);
      if (!previous) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const [updated] = await tx.update(individualHandovers).set({ deletedAt: null, completed: false, completedAt: null, updatedBy: actor.actorId, revision: previous.revision + 1 }).where(and(eq2(individualHandovers.id, input.id), eq2(individualHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "individual_handover", input.id, "restore", previous, updated);
      return updated;
    });
  }),
  hardDelete: appAdminProcedure.input(z2.object({ id: z2.string(), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(individualHandovers).where(eq2(individualHandovers.id, input.id)).limit(1);
      if (!previous) throw notFoundError();
      await tx.delete(individualHandovers).where(eq2(individualHandovers.id, input.id));
      await writeAudit(tx, actor, "individual_handover", input.id, "hard_delete", previous, null);
      return { success: true };
    });
  })
});
var customerInput = z2.object({
  id: z2.string().min(1).max(64),
  dateKey: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  customerName: z2.string().max(128),
  store: z2.string().max(64),
  content: z2.string().max(2048),
  status: z2.string().max(32),
  assignee: z2.string().max(64),
  links: z2.array(z2.string()).max(4).optional(),
  dueDate: z2.number().nullable().optional(),
  callCount: z2.number().int().min(0).max(2).optional(),
  expectedRevision,
  requestId: requestIdInput
});
var customerPatchInput = z2.object({
  id: z2.string().min(1).max(64),
  expectedRevision: z2.number().int().positive(),
  customerName: z2.string().max(128).optional(),
  store: z2.string().max(64).optional(),
  content: z2.string().max(2048).optional(),
  status: z2.string().max(32).optional(),
  assignee: z2.string().max(64).optional(),
  links: z2.array(z2.string()).max(4).optional(),
  dueDate: z2.number().nullable().optional(),
  callCount: z2.number().int().min(0).max(2).optional(),
  requestId: requestIdInput
});
var customerHandoverRouter = router({
  getActive: appProcedure.query(async () => {
    const db = await requireDb();
    return db.select().from(customerHandovers).where(and(isNull(customerHandovers.deletedAt), ne(customerHandovers.status, "\u5B8C\u4E86")));
  }),
  upsert: appProcedure.input(customerInput).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const current = await tx.select().from(customerHandovers).where(eq2(customerHandovers.id, input.id)).limit(1);
      const now = /* @__PURE__ */ new Date();
      const links = input.links ?? [];
      const dueDate = input.dueDate ?? null;
      const callCount = input.callCount ?? 0;
      if (current.length === 0) {
        if (input.expectedRevision != null) throw conflictError();
        const [created] = await tx.insert(customerHandovers).values({ ...input, links, dueDate, callCount, completedAt: input.status === "\u5B8C\u4E86" ? now : null, updatedBy: actor.actorId, revision: 1 }).returning();
        await writeAudit(tx, actor, "customer_handover", input.id, input.status === "\u5B8C\u4E86" ? "complete" : "create", null, created);
        return created;
      }
      const previous = current[0];
      if (previous.deletedAt) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const [updated] = await tx.update(customerHandovers).set({
        customerName: input.customerName,
        store: input.store,
        content: input.content,
        status: input.status,
        assignee: input.assignee,
        links,
        dueDate,
        callCount,
        completedAt: input.status === "\u5B8C\u4E86" ? previous.completedAt ?? now : null,
        updatedBy: actor.actorId,
        revision: previous.revision + 1
      }).where(and(eq2(customerHandovers.id, input.id), eq2(customerHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "customer_handover", input.id, input.status === "\u5B8C\u4E86" ? "complete" : "update", previous, updated);
      return updated;
    });
  }),
  patch: appProcedure.input(customerPatchInput).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(customerHandovers).where(eq2(customerHandovers.id, input.id)).limit(1);
      if (!previous || previous.deletedAt) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const updates = {};
      for (const key of ["customerName", "store", "content", "status", "assignee", "links", "dueDate", "callCount"]) {
        if (input[key] !== void 0) updates[key] = input[key];
      }
      if (Object.keys(updates).length === 0) {
        throw new TRPCError3({ code: "BAD_REQUEST", message: "\u66F4\u65B0\u3059\u308B\u9805\u76EE\u304C\u3042\u308A\u307E\u305B\u3093\u3002" });
      }
      if (updates.status === "\u5B8C\u4E86" && !previous.completedAt) updates.completedAt = /* @__PURE__ */ new Date();
      if (updates.status !== void 0 && updates.status !== "\u5B8C\u4E86") updates.completedAt = null;
      updates.updatedBy = actor.actorId;
      updates.revision = previous.revision + 1;
      const [updated] = await tx.update(customerHandovers).set(updates).where(and(eq2(customerHandovers.id, input.id), eq2(customerHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "customer_handover", input.id, updates.status === "\u5B8C\u4E86" ? "complete" : "update", previous, updated);
      return updated;
    });
  }),
  delete: appProcedure.input(z2.object({ id: z2.string(), expectedRevision: z2.number().int().positive(), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(customerHandovers).where(eq2(customerHandovers.id, input.id)).limit(1);
      if (!previous) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const [updated] = await tx.update(customerHandovers).set({ deletedAt: /* @__PURE__ */ new Date(), updatedBy: actor.actorId, revision: previous.revision + 1 }).where(and(eq2(customerHandovers.id, input.id), eq2(customerHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "customer_handover", input.id, "soft_delete", previous, updated);
      return updated;
    });
  }),
  restore: appProcedure.input(z2.object({ id: z2.string(), expectedRevision: z2.number().int().positive(), status: z2.string().max(32).optional(), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(customerHandovers).where(eq2(customerHandovers.id, input.id)).limit(1);
      if (!previous) throw notFoundError();
      assertExpectedRevision(previous.revision, input.expectedRevision);
      const status = input.status ?? previous.status;
      const [updated] = await tx.update(customerHandovers).set({
        deletedAt: null,
        status,
        completedAt: status === "\u5B8C\u4E86" ? previous.completedAt : null,
        updatedBy: actor.actorId,
        revision: previous.revision + 1
      }).where(and(eq2(customerHandovers.id, input.id), eq2(customerHandovers.revision, input.expectedRevision))).returning();
      if (!updated) throw conflictError();
      await writeAudit(tx, actor, "customer_handover", input.id, "restore", previous, updated);
      return updated;
    });
  }),
  hardDelete: appAdminProcedure.input(z2.object({ id: z2.string(), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    const actor = getAuditActor(ctx, input.requestId);
    return db.transaction(async (tx) => {
      const [previous] = await tx.select().from(customerHandovers).where(eq2(customerHandovers.id, input.id)).limit(1);
      if (!previous) throw notFoundError();
      await tx.delete(customerHandovers).where(eq2(customerHandovers.id, input.id));
      await writeAudit(tx, actor, "customer_handover", input.id, "hard_delete", previous, null);
      return { success: true };
    });
  })
});
var simpleStatusInput = z2.object({ value: z2.string().max(16), requestId: requestIdInput });
async function upsertSingletonStatus(db, table, field, value, actor, entityType) {
  return db.transaction(async (tx) => {
    const existing = await tx.select().from(table).limit(1);
    if (existing.length > 0) {
      const previous = existing[0];
      const [updated] = await tx.update(table).set({ [field]: value }).where(eq2(table.id, previous.id)).returning();
      await writeAudit(tx, actor, entityType, previous.id, "update", previous, updated);
      return updated;
    }
    const [created] = await tx.insert(table).values({ [field]: value }).returning();
    await writeAudit(tx, actor, entityType, created.id, "create", null, created);
    return created;
  });
}
var misocaRouter = router({
  get: appProcedure.query(async () => {
    const db = await requireDb();
    const result = await db.select().from(misocaStatus).limit(1);
    return result[0] ?? null;
  }),
  upsert: appProcedure.input(z2.object({ completedUntil: z2.string().max(16), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return upsertSingletonStatus(db, misocaStatus, "completedUntil", input.completedUntil, getAuditActor(ctx, input.requestId), "misoca_status");
  })
});
var grayCellRouter = router({
  get: appProcedure.query(async () => {
    const db = await requireDb();
    const result = await db.select().from(grayCellStatus).limit(1);
    return result[0] ?? null;
  }),
  upsert: appProcedure.input(z2.object({ confirmedUntil: z2.string().max(16), updatedBy: z2.string().max(64).default(""), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return db.transaction(async (tx) => {
      const existing = await tx.select().from(grayCellStatus).limit(1);
      const actor = getAuditActor(ctx, input.requestId);
      if (existing.length > 0) {
        const previous = existing[0];
        const [updated] = await tx.update(grayCellStatus).set({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy }).where(eq2(grayCellStatus.id, previous.id)).returning();
        await writeAudit(tx, actor, "gray_cell_status", previous.id, "update", previous, updated);
        return updated;
      }
      const [created] = await tx.insert(grayCellStatus).values({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy }).returning();
      await writeAudit(tx, actor, "gray_cell_status", created.id, "create", null, created);
      return created;
    });
  })
});
var storesShiftRouter = router({
  get: appProcedure.query(async () => {
    const db = await requireDb();
    const result = await db.select().from(storesShiftStatus).limit(1);
    return result[0] ?? null;
  }),
  upsert: appProcedure.input(z2.object({ confirmedUntil: z2.string().max(16), updatedBy: z2.string().max(64).default(""), requestId: requestIdInput })).mutation(async ({ ctx, input }) => {
    const db = await requireDb();
    return db.transaction(async (tx) => {
      const existing = await tx.select().from(storesShiftStatus).limit(1);
      const actor = getAuditActor(ctx, input.requestId);
      if (existing.length > 0) {
        const previous = existing[0];
        const [updated] = await tx.update(storesShiftStatus).set({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy }).where(eq2(storesShiftStatus.id, previous.id)).returning();
        await writeAudit(tx, actor, "stores_shift_status", previous.id, "update", previous, updated);
        return updated;
      }
      const [created] = await tx.insert(storesShiftStatus).values({ confirmedUntil: input.confirmedUntil, updatedBy: input.updatedBy }).returning();
      await writeAudit(tx, actor, "stores_shift_status", created.id, "create", null, created);
      return created;
    });
  })
});
var taskRouter = router({
  taskStates: taskStatesRouter,
  storeCheck: storeCheckRouter,
  individualHandover: individualHandoverRouter,
  customerHandover: customerHandoverRouter,
  misoca: misocaRouter,
  grayCell: grayCellRouter,
  storesShift: storesShiftRouter
});

// server/taskDefinitionRouter.ts
import { z as z3 } from "zod";
import { TRPCError as TRPCError4 } from "@trpc/server";
import { eq as eq3, asc, and as and2 } from "drizzle-orm";
var taskDefinitionRouter = router({
  // カテゴリ一覧＋各カテゴリのタスク定義を取得
  getAll: appProcedure.query(async () => {
    const db = await getDb();
    if (!db) {
      throw new TRPCError4({
        code: "INTERNAL_SERVER_ERROR",
        message: "\u30C7\u30FC\u30BF\u30D9\u30FC\u30B9\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093\u3002\u30C7\u30FC\u30BF\u306F\u5909\u66F4\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002"
      });
    }
    const categories = await db.select().from(taskCategories).where(eq3(taskCategories.isActive, true)).orderBy(asc(taskCategories.sortOrder));
    const definitions = await db.select().from(taskDefinitions).where(eq3(taskDefinitions.isActive, true)).orderBy(asc(taskDefinitions.sortOrder));
    return categories.map((cat) => ({
      ...cat,
      tasks: definitions.filter((d) => d.categoryId === cat.id)
    }));
  }),
  // ─── カテゴリ管理 ────────────────────────────────────────────────────────
  // カテゴリ追加
  addCategory: appAdminProcedure.input(
    z3.object({
      name: z3.string().min(1).max(128)
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    const existing = await db.select().from(taskCategories).where(eq3(taskCategories.isActive, true)).orderBy(asc(taskCategories.sortOrder));
    const maxSort = existing.length > 0 ? existing[existing.length - 1].sortOrder + 1 : 0;
    const [result] = await db.insert(taskCategories).values({
      name: input.name,
      sortOrder: maxSort,
      isActive: true
    }).returning({ id: taskCategories.id });
    return { id: result.id };
  }),
  // カテゴリ名変更
  updateCategory: appAdminProcedure.input(
    z3.object({
      id: z3.number(),
      name: z3.string().min(1).max(128)
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await db.update(taskCategories).set({ name: input.name }).where(eq3(taskCategories.id, input.id));
    return { success: true };
  }),
  // カテゴリ削除（配下のタスクも論理削除）
  deleteCategory: appAdminProcedure.input(z3.object({ id: z3.number() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await db.update(taskDefinitions).set({ isActive: false }).where(eq3(taskDefinitions.categoryId, input.id));
    await db.update(taskCategories).set({ isActive: false }).where(eq3(taskCategories.id, input.id));
    return { success: true };
  }),
  // カテゴリ並び替え（sortOrderを一括更新）
  reorderCategories: appAdminProcedure.input(
    z3.object({
      categories: z3.array(z3.object({ id: z3.number(), sortOrder: z3.number() }))
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await Promise.all(
      input.categories.map(
        ({ id, sortOrder }) => db.update(taskCategories).set({ sortOrder }).where(eq3(taskCategories.id, id))
      )
    );
    return { success: true };
  }),
  // ─── タスク管理 ────────────────────────────────────────────────────────
  // タスク追加
  addTask: appAdminProcedure.input(
    z3.object({
      categoryId: z3.number(),
      label: z3.string().min(1).max(512),
      defaultPlanned: z3.string().max(64).default("\u5F53\u65E5\u4E8B\u52D9\u62C5\u5F53"),
      deadline: z3.string().max(64).default("")
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    const existing = await db.select().from(taskDefinitions).where(
      and2(
        eq3(taskDefinitions.categoryId, input.categoryId),
        eq3(taskDefinitions.isActive, true)
      )
    ).orderBy(asc(taskDefinitions.sortOrder));
    const maxSort = existing.length > 0 ? existing[existing.length - 1].sortOrder + 1 : 0;
    const [result] = await db.insert(taskDefinitions).values({
      categoryId: input.categoryId,
      label: input.label,
      defaultPlanned: input.defaultPlanned,
      deadline: input.deadline,
      sortOrder: maxSort,
      isActive: true
    }).returning({ id: taskDefinitions.id });
    return { id: result.id };
  }),
  // タスク編集
  updateTask: appAdminProcedure.input(
    z3.object({
      id: z3.number(),
      label: z3.string().min(1).max(512).optional(),
      defaultPlanned: z3.string().max(64).optional(),
      deadline: z3.string().max(64).optional(),
      showOnDays: z3.string().max(128).optional()
      // 例: "15,30" = 毎月15日・30日のみ。空文字列 = 常時表示
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    const { id, ...updates } = input;
    await db.update(taskDefinitions).set(updates).where(eq3(taskDefinitions.id, id));
    return { success: true };
  }),
  // タスク論理削除
  deleteTask: appAdminProcedure.input(z3.object({ id: z3.number() })).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await db.update(taskDefinitions).set({ isActive: false }).where(eq3(taskDefinitions.id, input.id));
    return { success: true };
  }),
  // タスク並び替え（同カテゴリ内のsortOrderを一括更新）
  reorderTasks: appAdminProcedure.input(
    z3.object({
      // [{id, sortOrder}] の配列
      tasks: z3.array(z3.object({ id: z3.number(), sortOrder: z3.number() }))
    })
  ).mutation(async ({ input }) => {
    const db = await getDb();
    if (!db) throw new Error("DB not available");
    await Promise.all(
      input.tasks.map(
        ({ id, sortOrder }) => db.update(taskDefinitions).set({ sortOrder }).where(eq3(taskDefinitions.id, id))
      )
    );
    return { success: true };
  })
});

// server/routers.ts
var appRouter = router({
  // if you need to use socket.io, read and register route in server/_core/index.ts, all api should start with '/api/' so that the gateway can route correctly
  system: systemRouter,
  auth: router({
    me: publicProcedure.query((opts) => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return {
        success: true
      };
    })
  }),
  task: taskRouter,
  taskDefinition: taskDefinitionRouter
  // TODO: add feature routers here, e.g.
  // todo: router({
  //   list: protectedProcedure.query(({ ctx }) =>
  //     db.getUserTodos(ctx.user.id)
  //   ),
  // }),
});

// server/_core/supabaseAuth.ts
import { createClient } from "@supabase/supabase-js";
function getHeaderValue(headers, name) {
  const value = headers?.[name];
  return Array.isArray(value) ? value[0] : value;
}
function getAccessToken(req) {
  const authorization = getHeaderValue(req.headers, "authorization");
  if (!authorization?.startsWith("Bearer ")) return null;
  const token = authorization.slice("Bearer ".length).trim();
  return token || null;
}
function getAdminEmails() {
  return new Set(
    (process.env.ADMIN_EMAILS ?? "").split(",").map((email) => email.trim().toLowerCase()).filter(Boolean)
  );
}
function getSupabaseAuthConfig() {
  const url = process.env.VITE_SUPABASE_URL ?? "";
  const publishableKey = process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_ANON_KEY ?? "";
  return { url, publishableKey };
}
async function authenticateSupabaseRequest(req) {
  const token = getAccessToken(req);
  const { url, publishableKey } = getSupabaseAuthConfig();
  if (!token || !url || !publishableKey) return null;
  const supabase = createClient(url, publishableKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  });
  const { data, error } = await supabase.auth.getUser(token);
  const email = data.user?.email?.trim().toLowerCase();
  if (error || !data.user || !email || !getAdminEmails().has(email))
    return null;
  const createdAt = data.user.created_at ? new Date(data.user.created_at) : /* @__PURE__ */ new Date();
  const updatedAt = data.user.updated_at ? new Date(data.user.updated_at) : createdAt;
  const displayName = typeof data.user.user_metadata.full_name === "string" ? data.user.user_metadata.full_name : email;
  return {
    id: 0,
    openId: `supabase:${data.user.id}`,
    name: displayName,
    email,
    loginMethod: "supabase",
    role: "admin",
    createdAt,
    updatedAt,
    lastSignedIn: /* @__PURE__ */ new Date()
  };
}

// server/vercelTrpcHandler.ts
var config = {
  api: {
    bodyParser: false
  }
};
function appendSetCookie(res, cookie) {
  const current = res.getHeader("Set-Cookie");
  if (!current) {
    res.setHeader("Set-Cookie", cookie);
    return;
  }
  const values = Array.isArray(current) ? current : [String(current)];
  res.setHeader("Set-Cookie", [...values, cookie]);
}
function serializeClearedCookie(name, options) {
  const parts = [
    `${encodeURIComponent(name)}=`,
    "Expires=Thu, 01 Jan 1970 00:00:00 GMT",
    "Max-Age=0"
  ];
  if (options.domain) parts.push(`Domain=${options.domain}`);
  if (options.path) parts.push(`Path=${options.path}`);
  if (options.httpOnly) parts.push("HttpOnly");
  if (options.secure) parts.push("Secure");
  if (options.sameSite) {
    const sameSite = options.sameSite === true ? "Strict" : options.sameSite;
    parts.push(
      `SameSite=${sameSite.charAt(0).toUpperCase()}${sameSite.slice(1)}`
    );
  }
  return parts.join("; ");
}
function withExpressCookieCompat(res) {
  res.clearCookie = (name, options = {}) => {
    appendSetCookie(
      res,
      serializeClearedCookie(name, {
        domain: options.domain,
        httpOnly: options.httpOnly,
        path: options.path ?? "/",
        sameSite: options.sameSite,
        secure: options.secure
      })
    );
  };
  return res;
}
function getTrpcPath(req) {
  const queryPath = req.query?.trpc;
  if (Array.isArray(queryPath)) return queryPath.join("/");
  if (queryPath) return queryPath;
  const pathname = (req.url ?? "").split("?")[0] ?? "";
  return pathname.replace(/^\/api\/trpc\/?/, "");
}
async function handler(req, res) {
  const response = withExpressCookieCompat(res);
  await nodeHTTPRequestHandler({
    req,
    res: response,
    path: getTrpcPath(req),
    router: appRouter,
    createContext: async () => {
      let user = null;
      try {
        user = await authenticateSupabaseRequest(req);
      } catch {
        user = null;
      }
      return {
        req,
        res: response,
        user
      };
    }
  });
}
export {
  config,
  handler as default
};
